import { useEffect, useRef, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import {
  CheckCircle2,
  Clipboard,
  Copy,
  Download,
  FileImage,
  Loader2,
  ScanLine,
  Upload,
} from "lucide-react";
import { PageTransition } from "@/components/PageTransition";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useCountUp } from "@/hooks/useCountUp";
import { predictBoneAge } from "@/lib/api";
import { downloadPredictionReport } from "@/lib/report";
import { cn, formatFileSize, formatMonthsAsYears } from "@/lib/utils";

const acceptedExtensions = [".jpg", ".jpeg", ".png", ".dcm"];

function isAcceptedFile(file) {
  const lowerName = file.name.toLowerCase();
  return acceptedExtensions.some((extension) => lowerName.endsWith(extension));
}

function ResultCard({ title, children }) {
  return (
    <motion.div
      variants={{
        hidden: { opacity: 0, y: 16 },
        visible: { opacity: 1, y: 0 },
      }}
    >
      <Card className="min-h-36 p-5">
        <p className="text-sm font-semibold text-textMuted">{title}</p>
        <div className="mt-5 font-mono text-3xl font-bold text-primary">{children}</div>
      </Card>
    </motion.div>
  );
}

function AgeGauge({ months }) {
  const safeMonths = Math.max(0, Number(months) || 0);
  const percent = Math.min((safeMonths / 228) * 100, 100);

  return (
    <div className="rounded-xl border border-gray-100 bg-white p-6 shadow-sm">
      <div className="flex items-center justify-between font-mono text-xs font-semibold text-textMuted">
        <span>0 months</span>
        <span>228 months</span>
      </div>
      <div className="relative mt-5 h-12">
        <div className="absolute left-0 right-0 top-5 h-2 rounded-full bg-gray-100" />
        <div
          className="absolute left-0 top-5 h-2 rounded-full bg-accent"
          style={{ width: `${percent}%` }}
        />
        <div
          className="absolute top-2 flex -translate-x-1/2 flex-col items-center"
          style={{ left: `${percent}%` }}
        >
          <span className="h-8 w-8 rounded-full border-4 border-white bg-accent shadow-sm" />
          <span className="mt-2 whitespace-nowrap font-mono text-xs font-semibold text-primary">
            {Math.round(safeMonths)} months
          </span>
          <span className="text-xs text-textMuted">(Predicted)</span>
        </div>
      </div>
      <p className="mt-8 text-sm text-textMuted">Typical range: 0-228 months (0-19 years)</p>
    </div>
  );
}

function ClinicalNote({ result, gender }) {
  const months = Math.round(Number(result.bone_age_months) || 0);
  const { decimalYears } = formatMonthsAsYears(months);

  return (
    <Card className="p-6">
      <div className="flex items-center gap-3">
        <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-teal-50 text-accent">
          <Clipboard className="h-5 w-5" />
        </span>
        <h3 className="text-lg font-semibold text-primary">Clinical Note</h3>
      </div>
      <div className="mt-5 space-y-2 text-sm leading-7 text-textMuted">
        <p>
          <span className="font-semibold text-textPrimary">Predicted bone age:</span> {months} months (
          {decimalYears} years)
        </p>
        <p>
          <span className="font-semibold text-textPrimary">Gender:</span>{" "}
          {gender === "male" ? "Male" : "Female"}
        </p>
        <p>
          This estimate is generated by BoneAgeNet (EfficientNet-B3 + gender fusion) trained on
          12,611 RSNA pediatric X-rays with 8.01 months validation MAE (TTA). It is not a medical
          diagnosis. Please consult a radiologist for clinical decisions.
        </p>
      </div>
    </Card>
  );
}

export default function Predict() {
  const inputRef = useRef(null);
  const prefersReducedMotion = useReducedMotion();
  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState("");
  const [gender, setGender] = useState("");
  const [error, setError] = useState("");
  const [isDragging, setIsDragging] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);

  const predictedMonths = Math.round(Number(result?.bone_age_months) || 0);
  const animatedMonths = useCountUp(predictedMonths, 1200);
  const equivalentAge = formatMonthsAsYears(predictedMonths);
  const confidence = Math.round((result?.confidence || 0) * 100);
  const canPredict = Boolean(file && gender && !isLoading);

  useEffect(() => {
    if (!file || file.name.toLowerCase().endsWith(".dcm")) {
      setPreviewUrl("");
      return undefined;
    }

    const nextUrl = URL.createObjectURL(file);
    setPreviewUrl(nextUrl);

    return () => URL.revokeObjectURL(nextUrl);
  }, [file]);

  const handleFile = (nextFile) => {
    setResult(null);
    setCopied(false);

    if (!nextFile) return;

    if (!isAcceptedFile(nextFile)) {
      setFile(null);
      setError("Unsupported file format. Please upload a .jpg, .png, or .dcm file.");
      return;
    }

    setError("");
    setFile(nextFile);
  };

  const handlePredict = async () => {
    if (!canPredict) return;

    setIsLoading(true);
    setError("");

    try {
      const prediction = await predictBoneAge(file, gender);
      setResult({
        ...prediction,
        confidence: prediction.confidence ?? 0.9,
      });
    } catch (err) {
      setResult(null);
      setError(
        err?.response?.data?.detail ||
          "Prediction failed. Check the API connection or enable VITE_USE_MOCK=true.",
      );
    } finally {
      setIsLoading(false);
    }
  };

  const copyLink = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  };

  return (
    <PageTransition>
      <div className="grid gap-6 xl:grid-cols-[0.92fr_1.08fr]">
        <section className="space-y-6">
          <Card className="p-6">
            <h2 className="text-xl font-semibold text-primary">Input Panel</h2>
            <p className="mt-2 text-sm text-textMuted">Upload a left-hand X-ray and provide gender metadata.</p>

            <div
              className={cn(
                "mt-6 flex min-h-[320px] flex-col items-center justify-center rounded-xl border-2 border-dashed border-borderSoft bg-background px-5 py-8 text-center transition-colors",
                isDragging && "border-accent bg-teal-50",
                error && "border-error bg-red-50",
                file && !error && "border-accent bg-white",
              )}
              onDragOver={(event) => {
                event.preventDefault();
                setIsDragging(true);
              }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={(event) => {
                event.preventDefault();
                setIsDragging(false);
                handleFile(event.dataTransfer.files?.[0]);
              }}
            >
              {previewUrl ? (
                <img
                  src={previewUrl}
                  alt="Selected hand X-ray preview"
                  className="max-h-64 w-full object-contain"
                />
              ) : file?.name.toLowerCase().endsWith(".dcm") ? (
                <div className="flex flex-col items-center">
                  <FileImage className="h-14 w-14 text-accent" />
                  <p className="mt-4 font-semibold text-primary">DICOM File Ready</p>
                </div>
              ) : (
                <div className="flex flex-col items-center">
                  <ScanLine className="h-16 w-16 text-accent" />
                  <p className="mt-5 text-xl font-semibold text-primary">Drag X-ray Here</p>
                  <p className="mt-2 text-sm text-textMuted">or</p>
                  <Button
                    type="button"
                    variant="outline"
                    className="mt-3"
                    onClick={() => inputRef.current?.click()}
                  >
                    <Upload className="h-4 w-4" />
                    Browse File
                  </Button>
                  <p className="mt-5 font-mono text-xs font-semibold text-textMuted">
                    Accepts: .jpg .png .dcm
                  </p>
                  <p className="mt-1 text-xs text-textMuted">Left hand X-ray images only</p>
                </div>
              )}
              <input
                ref={inputRef}
                type="file"
                className="hidden"
                accept=".jpg,.jpeg,.png,.dcm,image/jpeg,image/png,application/dicom"
                onChange={(event) => handleFile(event.target.files?.[0])}
              />
            </div>

            <div className="mt-4 min-h-12" aria-live="polite">
              {file && !error && (
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <p className="text-sm font-semibold text-primary">{file.name}</p>
                    <p className="text-xs text-textMuted">{formatFileSize(file.size)}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge>
                      <CheckCircle2 className="h-3.5 w-3.5" />
                      Image Ready
                    </Badge>
                    <Button type="button" variant="ghost" size="sm" onClick={() => inputRef.current?.click()}>
                      Change
                    </Button>
                  </div>
                </div>
              )}
              {error && <p className="text-sm font-semibold text-error">{error}</p>}
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="text-sm font-semibold text-primary">Patient Gender</h3>
            <div className="mt-4 grid grid-cols-2 gap-3">
              {["male", "female"].map((option) => (
                <label
                  key={option}
                  className={cn(
                    "flex cursor-pointer items-center justify-center rounded-full border px-4 py-3 text-sm font-semibold transition-colors",
                    gender === option
                      ? "border-accent bg-accent text-white"
                      : "border-borderSoft bg-white text-textMuted hover:border-accent hover:text-primary",
                  )}
                >
                  <input
                    type="radio"
                    name="gender"
                    value={option}
                    checked={gender === option}
                    onChange={(event) => setGender(event.target.value)}
                    className="sr-only"
                  />
                  {option === "male" ? "Male" : "Female"}
                </label>
              ))}
            </div>
          </Card>

          <Button
            type="button"
            size="lg"
            className="h-14 w-full rounded-xl"
            disabled={!canPredict}
            onClick={handlePredict}
          >
            {isLoading ? (
              <>
                <Loader2 className="h-5 w-5 animate-spin" />
                Analyzing X-ray...
              </>
            ) : (
              <>
                <ScanLine className="h-5 w-5" />
                Predict Bone Age
              </>
            )}
          </Button>
        </section>

        <section className="space-y-6">
          {!result ? (
            <Card className="flex min-h-[540px] items-center justify-center p-8 text-center">
              <div>
                <ScanLine className="mx-auto h-14 w-14 text-accent" />
                <p className="mt-5 max-w-sm text-lg font-semibold text-primary">
                  Upload an X-ray and click Predict to see results.
                </p>
                <p className="mt-2 text-sm text-textMuted">Mock mode is available with VITE_USE_MOCK=true.</p>
              </div>
            </Card>
          ) : (
            <motion.div
              className="space-y-6"
              initial="hidden"
              animate="visible"
              variants={{
                hidden: {},
                visible: {
                  transition: {
                    staggerChildren: prefersReducedMotion ? 0 : 0.08,
                  },
                },
              }}
            >
              <div className="grid gap-4 md:grid-cols-3">
                <ResultCard title="Bone Age">
                  {animatedMonths}
                  <span className="ml-2 text-base text-textMuted">months</span>
                </ResultCard>
                <ResultCard title="Equivalent Age">
                  {equivalentAge.years}
                  <span className="ml-2 text-base text-textMuted">years</span>
                  <br />
                  <span className="text-2xl">{equivalentAge.months}</span>
                  <span className="ml-2 text-base text-textMuted">months</span>
                </ResultCard>
                <ResultCard title="Confidence">{confidence}%</ResultCard>
              </div>

              <motion.div variants={{ hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0 } }}>
                <AgeGauge months={predictedMonths} />
              </motion.div>

              <motion.div variants={{ hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0 } }}>
                <ClinicalNote result={result} gender={gender} />
              </motion.div>

              <motion.div
                className="flex flex-col gap-3 sm:flex-row"
                variants={{ hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0 } }}
              >
                <Button
                  type="button"
                  variant="outline"
                  className="rounded-xl"
                  onClick={() => downloadPredictionReport({ result, gender })}
                >
                  <Download className="h-4 w-4" />
                  Download Report (PDF)
                </Button>
                <Button type="button" variant="ghost" className="rounded-xl" onClick={copyLink}>
                  <Copy className="h-4 w-4" />
                  {copied ? "Link Copied" : "Copy Link"}
                </Button>
              </motion.div>
            </motion.div>
          )}
        </section>
      </div>
    </PageTransition>
  );
}
