const escapePdfText = (value) =>
  String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)");

export function downloadPredictionReport({ result, gender }) {
  const months = Number(result?.bone_age_months || 0);
  const years = Math.floor(months / 12);
  const remainingMonths = Math.round(months % 12);
  const confidence = Math.round((result?.confidence || 0) * 100);

  const lines = [
    { text: "Epiphyse Bone Age Report", size: 18, bold: true },
    { text: "" },
    { text: `Predicted bone age: ${months} months`, size: 12 },
    { text: `Equivalent age: ${years} years ${remainingMonths} months`, size: 12 },
    { text: `Gender: ${gender}`, size: 12 },
    { text: `Confidence: ${confidence}%`, size: 12 },
    { text: "" },
    {
      text:
        "This estimate is generated by an AI model trained on RSNA pediatric X-rays. It is not a medical diagnosis.",
      size: 10,
    },
    { text: "Consult a radiologist for clinical decisions.", size: 10 },
  ];

  const commands = ["BT"];
  let y = 720;

  lines.forEach((line) => {
    const font = line.bold ? "F2" : "F1";
    const size = line.size || 12;

    if (line.text === "") {
      y -= 18;
      return;
    }

    commands.push(`/${font} ${size} Tf`);
    commands.push(`72 ${y} Td (${escapePdfText(line.text)}) Tj`);
    commands.push(`-${72} -${y} Td`);
    y -= size + 10;
  });

  commands.push("ET");
  const content = commands.join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "epiphyse-bone-age-report.pdf";
  anchor.click();
  URL.revokeObjectURL(url);
}
